<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MTG.Run</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MTG.Core\MTG.Core.csproj" />
    <ProjectReference Include="..\MTG.DB\MTG.DB.csproj" />
    <ProjectReference Include="..\MTG.Engine\MTG.Engine.csproj" />
    <ProjectReference Include="..\MTG.Opponent\MTG.Opponent.csproj" />
    <ProjectReference Include="..\MTG.Resources\MTG.Resources.csproj" />
    <ProjectReference Include="..\MTG.Scryfall\MTG.Scryfall.csproj" />
  </ItemGroup>

</Project>
